import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import QueryProvider from "@/utils/queryprovider/queryprovider";
import Wrapper from "@/app/layout/wrapper/wrapper";
import CustomThemeProvider from "@/utils/themeprovider/theme.provider";
import { ToastContainer } from "react-toastify";

// Ensure font paths are correct
const geistSans = localFont({
  src: "/fonts/GeistVF.woff", // Adjust path based on actual location
  variable: "--font-geist-sans",
});

const geistMono = localFont({
  src: "/fonts/GeistMonoVF.woff", // Adjust path based on actual location
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          <CustomThemeProvider>
            <ToastContainer />
            <Wrapper>
              {children}
              
            </Wrapper>
          </CustomThemeProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
